apiVersion: v2
name: lgtm-stack
description: A Helm chart to deploy the LGTM telemetry stack (Loki, Grafana, Tempo, Mimir, Alloy) along with Node.js and Python microservices on EKS.
type: application
version: 0.1.0
appVersion: "1.0.0"
